### ISSUE TITLE
Event handling doesn't use _conditional_lower

### ISSUE THREAD

**Issue by Ethan-Bierlein** [ShearOfDoom/Cactus#38] opened 2015-06-08 16:33 UTC
_(This assumes that `lower_text` has been enabled)_

Suppose I have a `MapPosition` instance with the name `"My Position"`. If I try to assign a function to it using an event handler, and it's actual, capitalized name, it doesn't work. Here's an example.

```
"map_position.My Position.enter.after": func # <-- This doesn't work.
```

In order to get this to work, I have to type the following instead.

```
"map_position.my position.enter.after": func # <-- This works, but it's still a bug.
```

**Comment by mathvav** [comment] 2015-06-09 03:50
Duplicate of https://github.com/ShearOfDoom/Cactus/issues/30

**Closed as completed by mathvav** 2015-06-09 03:50 UTC
Labels: bug, duplicate, enhancement
